package:
  name: htslib
  version: "1.3"
build:
  number: 0
source:
  fn: htslib-1.3.tar.bz2
  url: https://github.com/samtools/htslib/releases/download/1.3/htslib-1.3.tar.bz2
requirements:
  build:
  run:

about:
  home: https://github.com/samtools/htslib
  license: MIT
  summary: C library for high-throughput sequencing data formats
