about:
  home: http://www.qiime.org
  license: GPL2
  summary: 'QIIME: Quantitative Insights Into Microbial Ecology'
build:
  number: 0
  skip: True    # [py3k]
package:
  name: qiime
  version: 1.9.1
requirements:
  build:
  - python
  - numpy ==1.9
  - pandas ==0.16
  - matplotlib ==1.4
  - scipy ==0.14
  - requests ==2.7
  - pickleshare ==0.5
  - simplegeneric ==0.8.1
  - traitlets ==4.0.0
  - decorator ==4.0.4
  - setuptools_scm ==1.8.0
  - path.py ==8.1.2
  - pexpect ==3.3
  - ipython ==4.0.0
  - ipython_genutils ==0.1.0
  - pbr ==1.3.0
  - lockfile ==0.10.2
  - cachecontrol ==0.11.5
  - bz2file ==0.98
  - cogent ==1.5.3
  - natsort ==3.5.0
  - pynast ==1.2.2
  - biom-format ==2.1.4
  - emperor ==0.9.51
  - qcli ==0.1.1
  - burrito ==0.9.1
  - burrito-fillings ==0.1.1
  - qiime-default-reference ==0.1.3
  - contextlib2 ==0.4.0
  - future ==0.15.2
  - nose ==1.3.7
  - six ==1.9.0
  - pytz ==2015.6
  - python-dateutil ==2.4.2
  - scikit-bio ==0.2.3
  - gdata ==2.0.18
  run:
  - python
  - numpy ==1.9
  - pandas ==0.16
  - matplotlib ==1.4
  - scipy ==0.14
  - requests ==2.7
  - pickleshare ==0.5
  - simplegeneric ==0.8.1
  - traitlets ==4.0.0
  - decorator ==4.0.4
  - setuptools_scm ==1.8.0
  - path.py ==8.1.2
  - pexpect ==3.3
  - ipython ==4.0.0
  - ipython_genutils ==0.1.0
  - pbr ==1.3.0
  - lockfile ==0.10.2
  - cachecontrol ==0.11.5
  - bz2file ==0.98
  - cogent ==1.5.3
  - natsort ==3.5.0
  - pynast ==1.2.2
  - biom-format ==2.1.4
  - emperor ==0.9.51
  - qcli ==0.1.1
  - burrito ==0.9.1
  - burrito-fillings ==0.1.1
  - qiime-default-reference ==0.1.3
  - contextlib2 ==0.4.0
  - future ==0.15.2
  - nose ==1.3.7
  - six ==1.9.0
  - pytz ==2015.6
  - python-dateutil ==2.4.2
  - scikit-bio ==0.2.3
  - gdata ==2.0.18
source:
  fn: qiime-1.9.1.tar.gz
  sha256: c12dcdae1fe44762a49668276d7e93f487d87a0dc2ff8ca696ac0eff9d92a8a8
  url: https://pypi.python.org/packages/source/q/qiime/qiime-1.9.1.tar.gz
test:
  imports:
    - qiime
    - qiime.util
    - qiime.check_id_map
    - qiime.sort
