package:
  name: seqbuster
  version: '2.3'

source:
  git_url: https://github.com/lpantano/seqbuster
  git_tag: miraligner-2.3 

build:
  number: 2

test:
  commands:
    # skip test on build boxes since it requires java
    # - miraligner -Xms750m -Xmx750m -h

about:
  home: https://github.com/lpantano/seqbuster
  license: MIT
  summary: miRNA and isomiR annotation
