{% set version = "3.3" %}

package:
  name: cogent-magdoll
  version: {{ version }}

source:
  fn: cogent-magdoll_{{ version }}.tar.gz
  url: https://github.com/Magdoll/Cogent/archive/v{{ version }}.tar.gz
  sha256: f0ac1b18e45369c3f3842fb8339a829138006f5274a26b8d823d2c082088b04a

build:
  number: 0
  skip: True # [py3k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - networkx 1.10
    - scikit-image >=0.11.3
    - pulp
    - biopython
    - bx-python 0.7.3
    - mash
    - minimap2

test:
  imports:
    - Cogent

about:
  home: https://github.com/Magdoll/Cogent
  license:  Pacific Biosciences of California, Inc.
  summary: 'Cogent is a tool for reconstructing the coding genome using high-quality full-length transcriptome sequences.'
